# Generated by Django 4.0.2 on 2022-02-10 19:37

from django.contrib.auth.models import Group, ContentType, Permission
from django.db import migrations

from app_users.models import User


def add_group_permissions(apps, schema_editor):
    group, is_created = Group.objects.get_or_create(name='authors')
    if is_created:
        ct = ContentType.objects.get_for_model(User)
        permission = Permission.objects.create(
            codename='can_create_articles',
            name='Can create new articles',
            content_type=ct
        )
        group.permissions.add(permission)

    group, is_created = Group.objects.get_or_create(name='subscribers')
    if is_created:
        ct = ContentType.objects.get_for_model(User)

        permission = Permission.objects.create(
            codename='can_view_privates',
            name='Can view private articles',
            content_type=ct
        )
        group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]

